---

- hosts: myhost  # playbook for database setup
  vars_files:
    - vars.yml
  tasks:
    ### MongoDB config
    - name: Add mongodb repo apt_key
      become: true
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    - name: Add mongodb sources list
      become: true
      shell: "echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list"
      changed_when: false
    - name: Update repositories cache and install "mongodb-org" package
      become: true
      apt: name=mongodb-org update_cache=yes
    - name: Start and enable mongod service
      become: true
      service: name=mongod state=started enabled=yes

    ### PostgreSQL config: http://blog.apcelent.com/using-ansible-to-set-up-postgresql.html
    - name: Install PostgreSQL
      become: true
      package: name="{{item}}" state=latest
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
    - name: Ensure the postgres service is running
      become: true
      service: name=postgresql state=started enabled=yes
    - name: Ensure postgres db is created
      become: true
      become_user: postgres
      postgresql_db: name={{ postgres_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
    - name: Ensure user created and can access db
      become: true
      become_user: postgres
      postgresql_user: db={{ postgres_name }}
                   name={{ postgres_user }}
                   password={{ postgres_pw }}
                   priv=ALL
                   state=present
    - name: Perform Django database migrations
      django_manage:
        command: migrate
        app_path: /home/ubuntu/jobpost_data

- hosts: myhost  # Supervisord + Celery config
  tasks:
    - name: Create celery user to be used by celeryd and celerybeatd
      become: true
      user:
        name: celery
    - name: Copy supervisord config
      become: true
      copy:
        src: ../supervisord.conf
        dest: /etc/supervisor/supervisord.conf
    - name: Restart supervisor service
      become: true
      service: name=supervisor state=restarted enabled=yes
